name: fleetpy
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0
  - numpy=2.2
  - plotly=5.24
  - python=3.10
  - scipy=1.15
  - pip:
    - cython==3.0.11
    - fiona==1.10.1
    - geopandas==1.0.1
    - pandas==2.2.3
    - pyogrio==0.10.0
    - pyproj==3.7.0
    - pyyaml==6.0.2
    - rtree==1.3.0
    - shapely==2.0.6
    - tqdm==4.67.1
    - dill==0.3.9
