#COMMUNICATION CODES
KILL = 0
INIT_OP = 1
LOAD_NEW_NETWORK_TRAVEL_TIMES = 2
SET_SIMTIME_AND_ACTIVE_REQUESTS = 3
COMPUTE_RR = 4
SET_RR = 5
SET_XTO1_TARGET_LOCATIONS = 6
RETURN_TARGETPOS_IN_TIMERANGE = 7
SET_RV_RESULTS = 8
UPDATE_V2RBS_AND_COMPUTE_NEW = 9
OPTIMIZE_BOARDING_POINTS_VID = 10
BATCH_SINGLE_INSERTION = 11
SET_DYN_SIMTIME_AND_ACTIVE_REQUESTS = 12
# ADDED  Moia Parallel
ADD_INIT_OP = 13
UPDATE_VEHICLE_PLANS_OFFER = 14
RESERVATION_INSERTION = 15
IMMEDIATE_INSERTION = 16